name: Build, test and lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust for Xtensa
      uses: esp-rs/xtensa-toolchain@v1.5
      with:
        default: true
        ldproxy: true
    
    - name: Build project
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy --no-deps -- -Dwarnings
