name: Build, test and lint

on:
  push:
    branches: [ "main-rust" ]
  pull_request:
    branches: [ "main-rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --no-deps -- -Dwarnings
